project:
  type: website

website:
  title: "Mermaid syntax demos in Quarto"
  navbar:
    left:
      - href: index.qmd
        text: Home
  
  sidebar:
    contents:
      - text: ğŸ“Š Diagram syntax
        contents: 
          - text: Flowchart
            href: syntax/flowchart.qmd
          - text: Sequence Diagram
            href: syntax/sequenceDiagram.qmd
          - text: Class Diagram
            href: syntax/classDiagram.qmd
          - text: State Diagram
            href: syntax/stateDiagram.qmd
          - text: Entity Relationship Diagram
            href: syntax/entityRelationshipDiagram.qmd
          - text: User Journey
            href: syntax/userJourney.qmd
          - text: Gantt
            href: syntax/gantt.qmd
          - text: Pie Chart
            href: syntax/pie.qmd
          - text: Requirement Diagram
            href: syntax/requirementDiagram.qmd
          - text: Gitgraph (Git) Diagram ğŸ”¥
            href: syntax/gitgraph.qmd
          - text: C4C Diagram (Context) Diagram ğŸ¦ºâš ï¸
            href: syntax/c4c.qmd
          - text: Mindmaps ğŸ”¥
            href: syntax/mindmap.qmd
          - text: Timeline ğŸ”¥
            href: syntax/timeline.qmd
          - syntax/examples.qmd


format:
  html:
    theme:
      light: flatly
      dark: darkly
    toc: true



